---
title: "01_clean_PSQI"
author: "Minji NAM"
date: "2025-05-13"
output: html_document
---

*Name* : 01_clean_PSQI
*Project* : Santé reproductive, infertilité et **complications de la grossesse** chez les femmes atteintes d'endométriose
*Description* : Preprocessing Data
*Date of creation* : 2025-05-13
*Date of update* : 2025-05-13
*Author* : stagiaire M2 Big Data in Health
*R version* : R version 4.4.2

---

$Libraries$
```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(stringr)
library(tableone)
library(nnet)
library(broom)
library(gtsummary)
library(rlang) 
library(labelled)
library(questionr)
library(guideR)
library(jmv)
library(nnet)
library(stringi)
```

# 0. Import the raw dataset 

```{r}
#-----------------------
# Import a main dataset
#-----------------------
PSQI <- read.csv(
  "Complic_pop_QST_0336_20250407_PSQI.csv",
  encoding = "latin1",
  colClasses = c(Sexe = "character")
)

#-----------------------------------------------
# Replace cells with nothing or spaces with NA
#-----------------------------------------------
PSQI <- PSQI %>% 
  mutate(across(everything(), ~na_if(trimws(.), "")),
         across(everything(), str_trim))

#-------------------------------------
# Remove all columns having only NAs
#-------------------------------------
na_count <- PSQI %>% sapply(function(x) sum(is.na(x))) #; na_count
index_col_NA <- which(na_count==nrow(PSQI)) %>% as.vector() # index of columns having only NA
```

# I. Preprocessing Data

```{r}
PSQI <-  PSQI %>% 
  mutate(PSQI = as.numeric(PSQI))

#---------------------------
#  Participation : Yes/No
#---------------------------
PSQI <- PSQI %>% 
  mutate(PSQI_participated=ifelse(is.na(IdAction),
                                  "Non","Oui"))
```

# II. Final dataset

```{r}
PSQI_final <-  PSQI %>%
  distinct(id_unik, 
           IdAction, 
           psqif, 
           PSQI_participated) %>% 
  mutate(psqif = case_when(
    is.na(IdAction) ~ "Not_answered",
    TRUE  ~ psqif
    )) %>%
  select(-IdAction)
```

# III. Save the final dataframe 

```{r}
#write.csv(PSQI_final,"PSQI_final.csv")
```


